export const FETCH_CHARACTERS_BEGIN = 'CHARACTERS/FETCH_CHARACTERS_BEGIN';
export const FETCH_CHARACTERS_SUCCESS = 'CHARACTERS/FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_FAILURE = 'CHARACTERS/FETCH_CHARACTERS_FAILURE';
export const CHANGE_PAGE = 'CHARACTERS/CHANGE_PAGE';
export const SET_SPECIES = 'CHARACTERS/SET_SPECIES';
export const SET_STATUS = 'CHARACTERS/SET_STATUS';
export const SET_GENDER = 'CHARACTERS/SET_GENDER';