export const FETCH_EPISODES_BEGGIN = 'EPISODES/FETCH_EPISODES_BEGGIN';
export const FETCH_EPISODES_SUCCESS = 'EPISODES/FETCH_EPISODES_SUCCESS';
export const FETCH_EPISODES_FAILURE = 'EPISODES/FETCH_EPISODES_FAILURE';
export const CHANGE_PAGE = 'EPISODES/CHANGE_PAGE';
export const SET_SEARCH = 'EPISODES/SET_SEARCH';
