export const FETCH_LOCATIONS_BEGIN = 'LOCATIONS/FETCH_LOCATIONS_BEGIN'; 
export const FETCH_LOCATIONS_SUCCESS = 'LOCATIONS/FETCH_LOCATIONS_SUCCESS'; 
export const FETCH_LOCATIONS_FAILURE = 'LOCATIONS/FETCH_LOCATIONS_FAILURE'; 
export const CHANGE_PAGE = 'LOCATIONS/CHANGE_PAGE';
export const SET_NAME = 'LOCATIONS/SET_NAME';
export const SET_TYPE = 'LOCATIONS/SET_TYPE';
export const SET_DIMENSION = 'LOCATIONS/SET_DIMENSION';